### ISSUE TITLE
eps in cpu test heavily affected by specifying 'cpuset' or not

### ISSUE THREAD

**Issue by xial-thu** [akopytov/sysbench#363]
I'm running sysbench in kubernetes with cpu-manager-policy enabled, which in general enables cpuset in containers. I find that eps in container with cpuset specified and that without are quite different.

sysbench version: sysbench 1.0.17

my yaml 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: guarantee-cpu2
spec:
  parallelism: 2
  backoffLimit: 0
  template:
    spec:
      nodeName: sh-idc1-10-121-2-130
      restartPolicy: Never
      containers:
        - command:
          - sysbench
          args:
          - cpu
          - --report-interval=1
          - --threads=4
          - --time=6000
          - run
          image: xxxxx
          resources:
            limits:
              cpu: 4
              memory: 200Mi
            requests:
              cpu: 4
              memory: 200Mi
          name: cpu
```

In one container, its cpu limit is 4, cpuset is 5-6,37-38 ,and eps is about 2100. 

However, in another container, its cpu limit is still 4, but cpuset is not set so it's 0-3,9-34,41-63. The eps is 3100

I'm confused why the results differ so much? Is it reasonable? Please help
